name: build+tag+push image to docker hub
on:
  push:
    branches: main
jobs:
  execute:
    runs-on: "ubuntu-latest"
    name: "executing process"
    steps:
      - name: generate specific version tag
        run: |
          TIMESTAMP=$(date -u +"%Y%m%d%H%M%S")
          SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-7)
          echo "IMAGE_VERSION_TAG=${TIMESTAMP}-${SHORT_SHA}" >> $GITHUB_ENV

      - name: setup checkout
        uses: actions/checkout@v4.2.2
        with:
          ref: main

      - name: setup docker builder
        uses: docker/setup-buildx-action@v3.7.1

      - name: setup docker metadata
        uses: docker/metadata-action@v5
        with:
          images: vembry/app

      - name: login to docker hub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{secrets.DOCKERHUB_ACCESS_USER}}
          password: ${{secrets.DOCKERHUB_ACCESS_TOKEN}}

      - name: build and push image to docker
        uses: docker/build-push-action@v6.10.0
        with:
          context: .
          push: true
          target: release
          tags: |
            vembry/broker:latest
            vembry/broker:${{env.IMAGE_VERSION_TAG}}

      - name: log out from docker hub
        run: docker logout
